"""
schemas/session.py — Core Pydantic models for GameSense sessions.

These models cross all boundaries: API responses, agent I/O, and database rows.
Nothing passes through the system as raw dicts — always these models.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


# ── Enums as Literals (avoids an extra import, works with Pydantic v2) ────────

MomentType = Literal["kill", "death", "clutch", "error", "strategy_break", "highlight", "blunder"]
SessionStatus = Literal["active", "processing", "complete", "failed"]
AnalysisStatus = Literal["pending", "complete", "failed"]
HighlightStatus = Literal["pending", "generating", "complete", "failed"]


# ── Score ─────────────────────────────────────────────────────────────────────

class Score(BaseModel):
    """Breakdown of the player's performance score for a session."""

    overall: int = Field(..., ge=0, le=100, description="Overall skill score 0-100")
    mechanics: int = Field(..., ge=0, le=100, description="Aim, movement, mechanics")
    decision_making: int = Field(..., ge=0, le=100, description="Strategic choices, positioning")
    consistency: int = Field(..., ge=0, le=100, description="Consistency across the session")

    model_config = {"frozen": True}


# ── Moment ────────────────────────────────────────────────────────────────────

class Moment(BaseModel):
    """A significant in-game event detected by MomentAgent."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    type: MomentType
    timestamp_ms: int = Field(..., description="Milliseconds from session start")
    description: str = Field(..., description="What happened, as seen by the AI")
    significance: int = Field(..., ge=1, le=10, description="1=minor, 10=game-changing")
    clip_url: Optional[str] = Field(None, description="VideoDB stream URL once compiled")
    commentary: Optional[str] = Field(None, description="AI-written commentary for this moment")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Clip ──────────────────────────────────────────────────────────────────────

class Clip(BaseModel):
    """A compiled video clip for a single Moment."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    moment_id: str
    session_id: str
    stream_url: str = Field(..., description="VideoDB CDN stream URL — embed directly")
    start_time: float = Field(..., description="Clip start in seconds (clamped to >= 0)")
    end_time: float = Field(..., description="Clip end in seconds")
    commentary: str = Field(..., description="AI commentary explaining this clip")
    type: MomentType

    @property
    def duration(self) -> float:
        return self.end_time - self.start_time


# ── Briefing ──────────────────────────────────────────────────────────────────

class Briefing(BaseModel):
    """Pre-session coaching brief generated by BriefingAgent from player history."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    player_id: str
    coaching_paragraph: str = Field(..., description="Personalised coaching text")
    focus_areas: list[str] = Field(default_factory=list, description="Key areas to focus on today")
    session_count: int = Field(..., description="Number of sessions this brief is based on")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── AnalysisResult ────────────────────────────────────────────────────────────

class AnalysisResult(BaseModel):
    """Complete post-session analysis produced by AnalysisAgent."""

    session_id: str
    score: Score
    moments: list[Moment] = Field(default_factory=list)
    clips: list[Clip] = Field(default_factory=list)
    patterns: list[str] = Field(
        default_factory=list,
        description="Recurring behavioural patterns detected across the session",
    )
    summary: str = Field(..., description="AI-written session summary paragraph")
    status: AnalysisStatus = "pending"
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── HighlightReel ─────────────────────────────────────────────────────────────

class HighlightReel(BaseModel):
    """A highlight reel compiled from top moments with OmniVoice narration."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    stream_url: Optional[str] = Field(None, description="VideoDB stream URL once generated")
    duration: Optional[float] = None
    status: HighlightStatus = "pending"
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Session ───────────────────────────────────────────────────────────────────

class Session(BaseModel):
    """Top-level session record — one per gaming session."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    player_id: str
    game: str
    status: SessionStatus = "active"

    # VideoDB references
    video_id: Optional[str] = Field(None, description="VideoDB VideoAsset ID after export")
    rtstream_id: Optional[str] = Field(None, description="RTStream ID during live session")

    # Populated after analysis
    score: Optional[Score] = None
    moments_detected: int = 0
    highlights_url: Optional[str] = None

    started_at: datetime = Field(default_factory=datetime.utcnow)
    ended_at: Optional[datetime] = None


# ── History entry (lightweight, for trend graphs) ─────────────────────────────

class SessionSummary(BaseModel):
    """Lightweight session row returned by GET /history/{player_id}."""

    id: str
    game: str
    score: Optional[int] = None
    mechanics: Optional[int] = None
    decision_making: Optional[int] = None
    consistency: Optional[int] = None
    moments_detected: int = 0
    started_at: datetime
    ended_at: Optional[datetime] = None
